services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: readings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345